<?php
$lang['no_admin'] = 'You are not Administrator.';
$lang['No_query_info'] = 'It\'s important to check the reason for the action not having been executed. A missing table,  column or a table already in the database are correct signs. Only information about no access to a command or an error in the SQL syntax are incorrect signs. Should you have any doubts, you can look for the answer or ask a question at <a href="http://www.przemo.org/phpBB2/"tatger="_blank">http://www.przemo.org/phpBB2/</a> by pasting the line which hasn\'t been executed. Notice, you shouldn\'t use the file update.sql to make an update on your own because it doesn\'t contain all the necessary instructions!';
$lang['update_body'] = '<b>Forum modification to version phpBB modified v1.12.8 by Przemo</b></span><br /><span class="gensmall">Use to switch from original phpBB 2.0.* or update from any version of  phpBB modified by Przemo from: 1.5 to 1.12.7</span></td></tr><tr><td class="row2"><span class="gensmall"><b>Instruction:</b><br />Before updating make a copy of your forum just in case. Copy all the files and make a database copy in the Administrator\'s Control Panel or PhpMyAdmin<br /> Once you\'ve got your copy don\'t overwrite the forum files with the update files but first you should start the update aplication (one button below) 
<br />Now press <b>"Start Update"</b> Instructions which haven\'t been executed will be displayed. In the update of original phpBB as well as the update of a lower version of phpBB by Przemo most of the instructions won\'t be executed because this is a universal update aplication. ' . $lang['No_query_info'] . '<br />
When done overwrite your forum files with the files of my version. The order of this process has to go this way: first turning on the update and after that overwriting the files. If the order is different then you have to be logged in as the admin when copying the files, which might not work out well and it might mean using your earlier made copy :)
<br /><br />Good Luck.';
$lang['start_update'] = 'Start Update';
$lang['checksum_error'] = 'Wrong file checkcum <b>%s</b> ! (%s)<br />Try to copy file on the server.';
$lang['result'] = '<b>The result of updating a database to phpBB modified v1.12.8 by Przemo</b><br />Instructions executed: <b>%s</b>, not executed: <b>%s</b><br /><br />&#8226;Check the following SQL instructions<br /><span class="gensmall">' . $lang['No_query_info'] . '</span><br /><br />&#8226; Overwrite all files except <i><b>config.php</b></i><br />&#8226; Check in your Adminstrator\'s Control Panel: System Control, Take in account the logging ability of your catalogues<br />&#8226; If your updating from the original version of phpBB correct the ranks  in your Administrator\'s Control Panel and move them to the styles\' folder.<br />&#8226; <span class="gensmall"> You can use the file <a href="update_useragent.php" target="_blank">/scripts/update_useragent.php</a> to adjust the browser icons for "old" posts  (use after sending the files) </span><br />&#8226; Match the new Admin, JR Admin, Moderator colours and OnMouseOver colours in the Administrator\'s Control Panel and in your template data.';
$lang['failed'] = 'Failed';
$lang['query_ok'] = 'Success';
$lang['No_available_db'] = 'phpBB by Przemo work only with MySQL database.';

$lang['UA_time_exc'] = 'Page generating time has been exceeded. <br />Posts processed: <b>%s</b> z <b>%s</b> <br />Continue converting: %sContinue%s.';
$lang['UA_title'] = 'Update browser and system user agent';
$lang['UA_finished'] = 'Update finished.<br />Updated posts: <b>%s</b>';
$lang['UA_no_useragent'] = 'Unable to find a directory with user agent icons. <br />Please check if directory <i>templates/subSilver/images/user_agent</i> exists. If not - extract it from downloaded file. <br />In other way commit us this error on our forum: <a href="http://www.przemo.org/phpBB2/forum/">http://www.przemo.org/phpBB2/forum/</a>.';
$lang['Generate_file'] = 'Check to generate file with queries only<br />';
$lang['dangerous_files'] = 'WARNING: our script detected on your account files, which could be dangerous. Because the files below should not be in this directories, we really recommend to check all these files by hand and make sure, they does not contain exploit or any other dangerous code. If you are not sure, you could consult us on our forum <a href="http://www.przemo.org/phpBB2/forum/">http://www.przemo.org/phpBB2/forum/</a>. If you are 100% sure, these files belongs to you and they are safe, plase continue update';
?>