<?php
/***************************************************************************
 *				portal.php
 *				-------------------
 * begin		: Tuesday, 28.05.2003
 * copyright	: (C) 2003 Przemo http://www.przemo.org
 * version		: 1.9
 ***************************************************************************/

/***************************************************************************
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 ***************************************************************************/


if (date("w") == 0) $td = "Niedziela";
if (date("w") == 1) $td = "Poniedzia³ek";
if (date("w") == 2) $td = "Wtorek";
if (date("w") == 3) $td = "¦roda";
if (date("w") == 4) $td = "Czwartek";
if (date("w") == 5) $td = "Pi±tek";
if (date("w") == 6) $td = "Sobota";
if (date("n") == 1) $md = "Stycznia";
if (date("n") == 2) $md = "Lutego";
if (date("n") == 3) $md = "Marca";
if (date("n") == 4) $md = "Kwietnia";
if (date("n") == 5) $md = "Maja";
if (date("n") == 6) $md = "Czerwca";
if (date("n") == 7) $md = "Lipca";
if (date("n") == 8) $md = "Sierpnia";
if (date("n") == 9) $md = "Wrze¶nia";
if (date("n") == 10) $md = "Pa¼dziernika";
if (date("n") == 11) $md = "Listopada";
if (date("n") == 12) $md = "Grudnia";

if ($data=="1-1") $birth_name = 'Mieczys³aw, Mas³aw, Mieczys³awa, Mieszko';
if ($data=="1-2") $birth_name = 'Abel, Izydor, Makary, Odil, Strze¿ys³aw';
if ($data=="1-3") $birth_name = 'Arletta, Danuta, Dan, Danisz, Enoch, Genowefa, Piotr, W³o¶cis³awa';
if ($data=="1-4") $birth_name = 'Angelika, Aniela, Benedykta, Benita, Dobromir, Dobrymir, Eugeniusz, Grzegorz, Izabela, Leonia, Rygobert, Tytus';
if ($data=="1-5") $birth_name = 'Edward, Emilian, Emiliusz, Hanna, Symeon, Szymon, Telesfor, W³o¶cibor';
if ($data=="1-6") $birth_name = 'Andrzej, Baltazar, Balcer, Bolemir, Epifania, Kacper, Kasper, Melchior';
if ($data=="1-7") $birth_name = 'Chocies³aw, Izydor, Julian, Lucjan, Walenty';
if ($data=="1-8") $birth_name = 'Erhard, M¶cis³aw, Seweryn';
if ($data=="1-9") $birth_name = 'Antoni, Bazylissa, Borzymir, Julian, Julianna, Marcelina, Marcjanna';
if ($data=="1-10") $birth_name = 'Agaton, Dobros³aw, Jan, Nikanor, Pawe³, Wilhelm';
if ($data=="1-11") $birth_name = 'Feliks, Hilary, Honorata, Hygin, Krzesimir, Matylda, Mechtylda';
if ($data=="1-12") $birth_name = 'Antoni, Arkadiusz, Arkady, Benedykt, Czes³aw, Czech, Czechasz, Czechoñ, Czes³awa, Ernest, Ernestyn, Greta, Reinhold, Tycjan';
if ($data=="1-13") $birth_name = 'Bogumi³, Bogus±d, Bogus³awa, Gotfryd, Godfryd, Leoncjusz, Melania, Weronika';
if ($data=="1-14") $birth_name = 'Feliks, Hilary, Odo, Radogost';
if ($data=="1-15") $birth_name = 'Aleksander, Dobrawa, D±brówka, Domas³aw, Domos³aw, Izydor, Makary, Maur, Pawe³';
if ($data=="1-16") $birth_name = 'Marcel, Waleriusz, W³odzimierz';
if ($data=="1-17") $birth_name = 'Antoni, Jan, Ro¶cis³aw';
if ($data=="1-18") $birth_name = 'Bogumi³, Jarope³k, Krystyna, Liberata, Ma³gorzata, Piotr, Pryska';
if ($data=="1-19") $birth_name = 'Andrzej, Bernard, Erwin, Erwina, Eufemia, Henryk, Kanut, Mariusz, Marta, Matylda, Mechtylda, Pia, Racimir, Sara';
if ($data=="1-20") $birth_name = 'Dobiegniew, Fabian, Sebastian';
if ($data=="1-21") $birth_name = 'Agnieszka, Epifani, Jaros³aw, Jaros³awa, Jeros³awa, Marcela';
if ($data=="1-22") $birth_name = 'Anastazy, Dobromys³, Gaudencjusz, Gaudenty, Marta, Wincenty';
if ($data=="1-23") $birth_name = 'Emerencja, Ildefons, Jan, Klemens, Maria, Rajmund, Rajmunda, Wrócis³awa';
if ($data=="1-24") $birth_name = 'Chwalibóg, Felicja, Mirogniew, Rafa³, Rafaela, Tymoteusz';
if ($data=="1-25") $birth_name = 'Mi³osz, Mi³owan, Mi³owit, Pawe³, Tatiana, Tacjanna';
if ($data=="1-26") $birth_name = 'Paula, Paulina, Polikarp, Skarbimir, Wanda';
if ($data=="1-27") $birth_name = 'Angelika, Ilona, Jan Chryzostom, Julian, Przybys³aw';
if ($data=="1-28") $birth_name = 'Agnieszka, Augustyn, Flawian, Ildefons, Julian, Karol, Leonidas, Piotr, Radomir, Roger, Waleriusz';
if ($data=="1-29") $birth_name = 'Franciszek Salezy, Gilda, Hanna, Walerian, Waleriana, Waleriusz, Zdzis³aw';
if ($data=="1-30") $birth_name = 'Adelajda, Feliks, Gerard, Gerarda, Gerhard, Hiacynta, Maciej, Marcin, Martyna, Sebastian';
if ($data=="1-31") $birth_name = 'Cyrus, Euzebiusz, Jan, Ksawery, Ludwik, Marceli, Marcelin, Marcelina, Piotr, Spycigniew, Wirgiliusz';
if ($data=="2-1") $birth_name = 'Brygida, Bryda, Dobrocha, Dobrochna, Ignacy, Iga, Ignacja, ¯egota, Pawe³, Siemirad';
if ($data=="2-2") $birth_name = 'Joanna, Korneliusz, Maria, Mi³os³awa';
if ($data=="2-3") $birth_name = 'B³a¿ej, Hipolit, Hipolita, Laurencjusz, Wawrzyniec, Maksym, Oskar, Stefan, Telimena, Uniemys³';
if ($data=="2-4") $birth_name = 'Andrzej, Gilbert, Jan, Joanna, Józef, Mariusz, Weronika, Witos³awa';
if ($data=="2-5") $birth_name = 'Adelajda, Agata, Aga, Albin, Izydor, Jakub, Jan, Justynian, Pawe³, Piotr, Strze¿ys³awa';
if ($data=="2-6") $birth_name = 'Angel, Angelus, Antoni, Bogdana, Bohdan, Bohdana, Dorota, Ksenia, Szymon, Tytus';
if ($data=="2-7") $birth_name = 'Romuald, Ryszard, Sulis³aw';
if ($data=="2-8") $birth_name = 'Gniewomir, Gniewosz, Honorat, Jan, Ksenofont, Lucjusz, Pawe³, Piotr, Salomon, Sebastian, ¯aklina';
if ($data=="2-9") $birth_name = 'Apolonia, Bernard, Cyryl, Eryk, Eryka, Gorzys³aw, Mariusz, Nikifor, Rajnold';
if ($data=="2-10") $birth_name = 'Elwira, Gabriel, Jacek, Jacenty, Scholastyka, Tomis³awa';
if ($data=="2-11") $birth_name = 'Adolf, Adolfa, Adolfina, Alf, Bernadetta, Dezydery, Eufrozyna, Lucjan, £azarz, Maria, Olgierd, ¦wiêtomira';
if ($data=="2-12") $birth_name = 'Aleksy, Benedykt, Eulalia, Julian, Laurenty, Modest, Nora, Radzim, Trzebis³awa';
if ($data=="2-13") $birth_name = 'Benigna, Grzegorz, Jordan, Kastor, Katarzyna, Klemens, Toligniew';
if ($data=="2-14") $birth_name = 'Adolf, Adolfa, Adolfina, Alf, Cyryl, Dobies³awa, Dobis³awa, Józef, Józefa, Konrad, Konrada, Krystyna, Liliana, Lilian, Miko³aj, Niemir, Niemira, Walenty, Zenon, Zenona';
if ($data=="2-15") $birth_name = 'Faustyn, Georgia, Georgina, Jordan, Jowita, Józef, Klaudiusz, Przybyrad, Sewer';
if ($data=="2-16") $birth_name = 'Bernard, Danuta, Dan, Danisz, Julianna, Symeon';
if ($data=="2-17") $birth_name = 'Donat, Donata, Franciszek, Izydor, Julian, Konstanty, £ukasz, Niegomir, Sylwin, Zbigniew, Zbyszko';
if ($data=="2-18") $birth_name = 'Albert, Alberta, Albertyna, Fryda, Konstancja, Krystiana, Maksym, Sawa, Sylwan, Sylwana, Symeon, Wiêces³awa, Zuzanna, Zula';
if ($data=="2-19") $birth_name = 'Arnold, Arnolf, B±dzis³awa, Gabin, Henryk, Konrad, Konrada, Leoncjusz, Manswet, Marceli';
if ($data=="2-20") $birth_name = 'Euchariusz, Eustachy, Eustachiusz, Leon, Ludmi³a, Ludomi³a, Ostap, Siestrzewit';
if ($data=="2-21") $birth_name = 'Eleonora, Feliks, Fortunat, Kiejstut, Teodor, Wyszeniega';
if ($data=="2-22") $birth_name = 'Ma³gorzata, Nikifor, Piotr, Wiktor, Wiktoriusz, Wrócis³aw';
if ($data=="2-23") $birth_name = 'B±dzimir, Damian, Florentyn, £azarz, Piotr, Romana, Roma, Seweryn';
if ($data=="2-24") $birth_name = 'Bogurad, Bogusz, Boguta, Bohusz, Lucjusz, Maciej, Piotr';
if ($data=="2-25") $birth_name = 'Bolebor, Cezary, Konstancjusz, Maciej, Ma³gorzata, Modest, Nicefor';
if ($data=="2-26") $birth_name = 'Aleksander, Bogumi³, Cezariusz, Dionizy, Miros³aw, Nestor';
if ($data=="2-27") $birth_name = 'Aleksander, Anastazja, Auksencjusz, Gabriel, Gabriela, Honoryna, Leander, Leonard, Sieros³awa';
if ($data=="2-28") $birth_name = 'Chwalibóg, Józef, Makary, Nadbor, Roman';
if ($data=="2-29") $birth_name = 'Dobronieg, Roman';
if ($data=="3-1") $birth_name = 'Albin, Antoni, Antonina, Budzis³aw, Budzisz, Eudoksja , Eudokia, Ewdokia, Jewdocha, Feliks, Herakles, Herkules, Joanna, Józef, Nikifor, Piotr';
if ($data=="3-2") $birth_name = 'Absalon, Franciszek, Halszka, Helena, Henryk, Januaria, Krzysztof, Lew, Micha³, Pawe³, Piotr, Rados³aw, Symplicjusz';
if ($data=="3-3") $birth_name = 'Asteriusz, Hieronim, Kunegunda, Lucjola, Maryna, Wierzchos³awa';
if ($data=="3-4") $birth_name = 'Adrian, Adrianna, Arkadiusz, Arkady, Eugeniusz, Kazimierz, Lew, Lucja, Lucjusz, £ucja, Wac³aw, Wac³awa';
if ($data=="3-5") $birth_name = 'Adrian, Adrianna, Fryderyk, Jan, Pakos³aw, Pakosz, Wac³aw, Wac³awa';
if ($data=="3-6") $birth_name = 'Eugenia, Felicyta, Frydolin, Jordan, Klaudian, Koleta, Ró¿a, Wiktor, Wiktoriusz, Wojs³aw';
if ($data=="3-7") $birth_name = 'Felicja, Nadmir, Pawe³, Polikarp, Tomasz';
if ($data=="3-8") $birth_name = 'Beata, Filemon, Jan, Julian, Mi³ogost, Miligost, Stefan, Wincenty';
if ($data=="3-9") $birth_name = 'Apollo, Dominik, Franciszka, Katarzyna, M¶cis³awa, Prudencjusz, Taras';
if ($data=="3-10") $birth_name = 'Aleksander, Bo¿ys³aw, Cyprian, Makary, Marceli, Porfirion';
if ($data=="3-11") $birth_name = 'Benedykt, Drogos³awa, Edwin, Kandyd, Konstanty, Konstantyn, Prokop, Rozyna, Sofroniusz';
if ($data=="3-12") $birth_name = 'Bernard, Blizbor, Grzegorz, Józefina, Wasyl';
if ($data=="3-13") $birth_name = 'Bo¿ena, Ernest, Ernestyn, Kasjan, Krystyna, Marek, Rodryg, Roderyk, Rodryk, Trzebis³aw';
if ($data=="3-14") $birth_name = 'Bo¿eciecha, Jakub, Leon, Matylda, Mechtylda, Micha³';
if ($data=="3-15") $birth_name = 'Go¶cimir, Klemens, Krzysztof, Longinus, Ludwika, Heloiza';
if ($data=="3-16") $birth_name = 'Abraham, Cyriak, Henryka, Herbert, Hiacynt, Hilary, Izabela, Oktawia';
if ($data=="3-17") $birth_name = 'Gertruda, Harasym, Jan, Patrycjusz, Patryk, Regina, Rena, Zbigniew, Zbyszko, Zbygniew';
if ($data=="3-18") $birth_name = 'Aleksander, Anzelm, Boguchwa³, Cyryl, Edward, Narcyz, Narcyza, Salwator';
if ($data=="3-19") $birth_name = 'Bogdan, Józef';
if ($data=="3-20") $birth_name = 'Aleksander, Aleksandra, Ambro¿y, Anatol, Bogus³aw, Cyriaka, Eufemia, Klaudia, Patrycjusz, Ruprecht, Wasyl, Wincenty';
if ($data=="3-21") $birth_name = 'Benedykt, Filemon, Lubomira, Miko³aj';
if ($data=="3-22") $birth_name = 'Bazylissa, Bogus³aw, Godzis³aw, Katarzyna, Kazimierz, Pawe³';
if ($data=="3-23") $birth_name = 'Eberhard, Feliks, Katarzyna, Kondrat, Oktawian, Pelagia, Pelagiusz, Piotr, Zbys³aw';
if ($data=="3-24") $birth_name = 'Dzier¿ys³awa, Dziers³awa, Gabor, Gabriel, Marek, Sewer, Sofroniusz, Szymon';
if ($data=="3-25") $birth_name = 'Dyzma, Ireneusz, Lucja, Lutomys³, £ucja, Maria, Mariola, Wieñczys³aw';
if ($data=="3-26") $birth_name = 'Emanuel, Manuela, Feliks, Larysa, Nikifor, Teodor, Tworzymir';
if ($data=="3-27") $birth_name = 'Benedykt, Ernest, Ernestyn, Jan, Lidia, Ro¶cimir, Rupert';
if ($data=="3-28") $birth_name = 'Aniela, Antoni, Jan, Krzesis³aw, Sykstus';
if ($data=="3-29") $birth_name = 'Cyryl, Czcirad, Eustachy, Eustachiusz, Ostap, Wiktoryn';
if ($data=="3-30") $birth_name = 'Amelia, Aniela, Czêstobor, Jan, Kwiryna, Kwiryn';
if ($data=="3-31") $birth_name = 'Amos, Balbina, Beniamin, Dobromira, Gwidon, Kiry³, Korneli, Kornelia';
if ($data=="4-1") $birth_name = 'Chryzant, Gra¿yna, Hugo, Hugon, Katarzyna, Teodora, Tolis³aw, Zbigniew, Zbyszko';
if ($data=="4-2") $birth_name = 'Franciszek, S±domir, Urban, W³adys³aw, W³adys³awa';
if ($data=="4-3") $birth_name = 'Antoni, Cieszygor, Jakub, Pankracy, Ryszard';
if ($data=="4-4") $birth_name = 'Ambro¿y, Bazyli, Benedykt, Izydor, Wac³aw, Wac³awa, Zdzimir';
if ($data=="4-5") $birth_name = 'Borzywoj, Irena, Wincenty';
if ($data=="4-6") $birth_name = 'Adam, Ada, Adamina, Celestyn, Celestyna, Diogenes, Ireneusz, Katarzyna, Sykstus, ¦wiêtobor, Wilhelm, Zachariasz';
if ($data=="4-7") $birth_name = 'Donat, Donata, Epifaniusz, Hegezyp, Herman, Przec³aw, Rufin';
if ($data=="4-8") $birth_name = 'Apolinary, Cezary, Cezaryna, Dionizy, Gawry³a, January, Rados³aw, Siecies³awa';
if ($data=="4-9") $birth_name = 'Dobros³awa, Dymitr, Maja, Marceli, Matron';
if ($data=="4-10") $birth_name = 'Antoni, Apoloniusz, Daniel, Ezechiel, Grodzis³aw, Henryk, Makary, Ma³gorzata, Micha³, Pompejusz';
if ($data=="4-11") $birth_name = 'Filip, Herman, Jaromir, Leon, Marek';
if ($data=="4-12") $birth_name = 'Andrzej, Iwan, Juliusz, Siemiodrog, Wiktor, Wiktoriusz, Zenon, Zenona';
if ($data=="4-13") $birth_name = 'Hermenegilda, Hermenegild, Ida, Jan, Justyn, Ma³gorzata, Przemys³, Przemys³aw';
if ($data=="4-14") $birth_name = 'Berenike, Julianna, Justyn, Maria, My¶limir, Tyburcjusz, Walerian, Waleriana';
if ($data=="4-15") $birth_name = 'Anastazja, Bazyli, Leonid, Ludwina, Modest, Olimpia, Tytus, Wac³aw, Wac³awa, Wiktoryn, Wszegniew';
if ($data=="4-16") $birth_name = 'Benedykt, Bernadetta, Cecyl, Cecylian, Charyzjusz, Erwin, Erwina, Julia, Ksenia, Lambert, Lamberta, Nikita, Nosis³aw, Patrycy, Urban';
if ($data=="4-17") $birth_name = 'Anicet, Innocenty, Innocenta, Jakub, Józef, Klara, Radociech, Robert, Roberta, Rudolf, Rudolfa, Rudolfina, Stefan';
if ($data=="4-18") $birth_name = 'Apoloniusz, Bogus³aw, Bogus³awa, Flawiusz, Go¶cis³aw';
if ($data=="4-19") $birth_name = 'Adolf, Adolfa, Adolfina, Alf, Cieszyrad, Czes³aw, Czech, Czechasz, Czechoñ, Leon, Leontyna, Pafnucy, Tymon, Werner, W³odzimierz';
if ($data=="4-20") $birth_name = 'Agnieszka, Amalia, Czes³aw, Czech, Czechasz, Czechoñ, Florencjusz, Florenty, Nawoj, Sulpicjusz, Szymon, Teodor';
if ($data=="4-21") $birth_name = 'Addar, Anzelm, Bartosz, Drogomi³, Feliks, Irydion, Konrad, Konrada, Selma';
if ($data=="4-22") $birth_name = 'Heliodor, Kajus, Leonia, Leonid, £ukasz, Soter, Strze¿ymir, Teodor';
if ($data=="4-23") $birth_name = 'Adalbert, Gerard, Gerarda, Gerhard, Helena, Jerzy, Wojciech';
if ($data=="4-24") $birth_name = 'Aleksander, Aleksy, Egbert, Erwin, Erwina, Fidelis, Grzegorz, Horacy, Horacjusz, Zbroimir';
if ($data=="4-25") $birth_name = 'Jaros³aw, Marek, Wasyl';
if ($data=="4-26") $birth_name = 'Artemon, Klaudiusz, Klet, Marcelin, Marcelina, Maria, Marzena, Spycimir';
if ($data=="4-27") $birth_name = 'Anastazy, Andrzej, Bo¿ebor, Kanizjusz, Martyn, Piotr, Teofil, Zyta';
if ($data=="4-28") $birth_name = 'Arystarch, Maria, Pawe³, Przybyczest, Waleria, Witalis';
if ($data=="4-29") $birth_name = 'Angelina, Augustyn, Bogus³aw, Hugo, Hugon, Paulin, Piotr, Rita, Robert, Roberta, Sybilla';
if ($data=="4-30") $birth_name = 'Bart³omiej, Chwalis³awa, Eutropiusz, Jakub, Katarzyna, Lilla, Marian';
if ($data=="5-1") $birth_name = 'Aniela, Filip, Jakub, Jeremiasz, Jeremi, Józef, Lubomir';
if ($data=="5-2") $birth_name = 'Anatol, Atanazy, Afanazy, Longin, Longina, Walenty, Walter, Witomir, Zygmunt';
if ($data=="5-3") $birth_name = 'Aleksander, Antonina, Maria, Mariola, ¦wiêtos³awa';
if ($data=="5-4") $birth_name = 'Florian, Grzegorz, January, Micha³, Monika, Paulin, Strze¿ywoj';
if ($data=="5-5") $birth_name = 'Irena, Ita, Pius, Teodor, Waldemar, Zdzibor';
if ($data=="5-6") $birth_name = 'Benedykta, Benita, Dytrych, Go¶ciwit, Jan, Judyta, Jurand';
if ($data=="5-7") $birth_name = 'Benedykt, Bogumir, Domicela, Flawia, Florian, Gizela, Gustawa, Ludmi³a, Ludomi³a, Sawa, Wincenta';
if ($data=="5-8") $birth_name = 'Dezyderia, Ilza, Marek, Micha³, Piotr, Stanis³aw';
if ($data=="5-9") $birth_name = 'Beatus, Bo¿ydar, Grzegorz, Job, Karolina, Miko³aj';
if ($data=="5-10") $birth_name = 'Antonin, Czêstomir, Izydor, Jan, Symeon, Wiktoryna';
if ($data=="5-11") $birth_name = 'Adalbert, Benedykt, Filip, Franciszek, Ignacy, Iga, Ignacja, ¯egota, Lew, Lutogniew, Mamert, Mira';
if ($data=="5-12") $birth_name = 'Domicela, Domicjan, Dominik, Epifani, Flawia, Jan, Jazon, Joanna, Pankracy, Wszemi³';
if ($data=="5-13") $birth_name = 'Andrzej, Aron, Ciechos³aw, Gloria, Magdalena, Piotr, Robert, Roberta, Serwacy';
if ($data=="5-14") $birth_name = 'Bonifacy, Boñcza, Dobies³aw, Jeremiasz, Jeremi, Wiktor, Wiktoriusz';
if ($data=="5-15") $birth_name = 'Atanazy, Afanazy, Berta, Cecyliusz, Czcibora, Dionizja, Izydor, Jan, Nadzieja, Ruprecht, Strze¿ys³aw, Zofia';
if ($data=="5-16") $birth_name = 'Andrzej, Honorat, Jan Nepomucen, Jêdrzej, Szymon, Trzebomys³, Ubald, Wieñczys³aw, Wiktorian';
if ($data=="5-17") $birth_name = 'Bruno, Herakliusz, Paschalis, S³awomir, Torpet, Weronika, Wiktor, Wiktoriusz';
if ($data=="5-18") $birth_name = 'Aleksander, Aleksandra, Alicja, Edwin, Eryk, Eryka, Feliks, Irina, Liboriusz, My¶libor, Wenancjusz';
if ($data=="5-19") $birth_name = 'Augustyn, Celestyn, Iwo, Miko³aj, Pêkos³aw, Piotr, Potencjana';
if ($data=="5-20") $birth_name = 'Anastazy, Asteriusz, Bazyli, Bazylid, Bazylis, Bernardyn, Bernardyna, Bronimir, Iwo, Sawa, Teodor, Wiktoria';
if ($data=="5-21") $birth_name = 'Donat, Donata, Jan, Kryspin, Przec³awa, Pudens, Tymoteusz, Walenty, Wiktor, Wiktoriusz';
if ($data=="5-22") $birth_name = 'Emil, Helena, Jan, Julia, Krzesis³awa, Rita, Wies³aw, Wies³awa, Wis³awa';
if ($data=="5-23") $birth_name = 'Budziwoj, Dezyderiusz, Dezydery, Emilia, Iwona, Jan, Leontyna, Micha³, Symeon';
if ($data=="5-24") $birth_name = 'Cieszys³awa, Estera, Jan, Joanna, Maria, Mokij, Wincenty, Zuzanna, Zula';
if ($data=="5-25") $birth_name = 'Epifan, Grzegorz, Imis³awa, Maria Magdalena, Urban';
if ($data=="5-26") $birth_name = 'Beda, Filip, Marianna, Paulina, Wiêcemi³, Wilhelmina';
if ($data=="5-27") $birth_name = 'Beda, Izydor, Jan, Juliusz, Lucjan, Magdalena, Radowit';
if ($data=="5-28") $birth_name = 'Augustyn, German, Jaromir, Priam, Wiktor, Wiktoriusz, Wilhelm, Wrócimir';
if ($data=="5-29") $birth_name = 'Bogus³awa, Maksymilian, Maria Magdalena, Teodor, Teodozja';
if ($data=="5-30") $birth_name = 'Andonik, Feliks, Ferdynand, Joanna, Sulimir';
if ($data=="5-31") $birth_name = 'Aniela, Bo¿ys³awa, Ernesta, Ernestyna, Feliks, Petronela, Petronia, Petroniusz, Teodor';
if ($data=="6-1") $birth_name = 'Alfons, Alfonsyna, Bernard, Fortunat, Gracjana, Hortensjusz, Jakub, Konrad, Konrada, Magdalena, Nikodem, Symeon, ¦wiêtope³k';
if ($data=="6-2") $birth_name = 'Efrem, Erazm, Eugeniusz, Marcelin, Maria, Marianna, Miko³aj, Nicefor, Piotr, Racis³aw';
if ($data=="6-3") $birth_name = 'Cecyliusz, Ferdynand, Klotylda, Konstantyn, Laurencjusz, Wawrzyniec, Laurentyn, Laurentyna, Leszek, Paula, Tamara';
if ($data=="6-4") $birth_name = 'Bazyliusz, Dacjan, Franciszek, Go¶cimi³, Karol, Karp';
if ($data=="6-5") $birth_name = 'Bonifacy, Boñcza, Dobrociech, Dobromir, Dobrymir, Nikanor, Waleria, Walter';
if ($data=="6-6") $birth_name = 'Benignus, Dominika, Klaudiusz, Laurenty, Norbert, Norberta, Paulina, Symeon, Wiêcerad';
if ($data=="6-7") $birth_name = 'Antoni, Ciechomir, Jaros³aw, Lukrecja, Pawe³, Robert, Roberta, Wies³aw, Wis³aw';
if ($data=="6-8") $birth_name = 'Karp, Maksym, Medard, Seweryn, Wilhelm, Wyszes³aw';
if ($data=="6-9") $birth_name = 'Felicjan, Pelagia, Pelagiusz';
if ($data=="6-10") $birth_name = 'Bogumi³, Edgar, Ma³gorzata, Mauryn, Nikita, Onufry';
if ($data=="6-11") $birth_name = 'Anastazy, Barnaba, Feliks, Radomi³, Teodozja';
if ($data=="6-12") $birth_name = 'Antonina, Bazyli, Jan, Leon, Onufry, Wyszemir';
if ($data=="6-13") $birth_name = 'Antoni, Chociemir, Herman, Lucjan, Maria Magdalena, Tobiasz';
if ($data=="6-14") $birth_name = 'Bazylid, Bazylis, Eliza, Justyn, Justyna, Ninogniew, Walerian, Waleriana';
if ($data=="6-15") $birth_name = 'Abraham, Angelina, Bernard, Jolanta, Leona, Leonida, Nikifor, Wit, Witold, Witolda, Wito³d, Witos³aw, Wodzis³aw';
if ($data=="6-16") $birth_name = 'Alina, Aneta, Benon, Budzimir, Jan, Justyna, Ludgarda';
if ($data=="6-17") $birth_name = 'Adolf, Adolfa, Adolfina, Alf, Agnieszka, Drogomys³, Franciszek, Laura, Marcjan, Radomi³, Rainer, Wolmar';
if ($data=="6-18") $birth_name = 'Efrem, El¿bieta, Gerwazy, Leonia, Marek, Marina, Paula';
if ($data=="6-19") $birth_name = 'Borzys³aw, Gerwazy, Julianna, Odo, Protazy, Sylweriusz';
if ($data=="6-20") $birth_name = 'Bogna, Bogumi³a, Bo¿ena, Florentyna, Franciszek, Micha³, Rafa³, Rafaela, Sylwery';
if ($data=="6-21") $birth_name = 'Albaniusz, Alicja, Alojzy, Alojza, Demetria, Domamir, Marta, Rudolf, Rudolfa, Rudolfina, Teodor';
if ($data=="6-22") $birth_name = 'Achacjusz, Achacy, Agenor, Alban, Broniwoj, Flawiusz, Innocenty, Innocenta, Kiry³, Paulina';
if ($data=="6-23") $birth_name = 'Agrypina, Albin, Bazyli, Józef, Piotr, Prosper, Wanda, Zenon, Zenona';
if ($data=="6-24") $birth_name = 'Danuta, Dan, Danisz, Emilia, Jan, Wilhelm';
if ($data=="6-25") $birth_name = 'Albrecht, Eulogiusz, Lucja, £ucja, Tolis³awa, Wilhelm';
if ($data=="6-26") $birth_name = 'Jan, Jeremiasz, Jeremi, Pawe³, Zdziwoj';
if ($data=="6-27") $birth_name = 'Maria Magdalena, W³adys³aw, W³adys³awa, W³odzis³aw';
if ($data=="6-28") $birth_name = 'Amos, Ireneusz, Józef, Leon, Pawe³, Raissa, Zbros³aw';
if ($data=="6-29") $birth_name = 'Benedykta, Benita, Dalebor, Pawe³, Piotr';
if ($data=="6-30") $birth_name = 'Alpinian, Ciechos³awa, Cyryl, Emilia, Lucyna, Marcjal';
if ($data=="7-1") $birth_name = 'Aaron, Bogus³aw, Halina, Klarysa, Marian, Niegos³awa, Teobald';
if ($data=="7-2") $birth_name = 'Juda, Maria, Martynian, Otto, Piotr, Urban';
if ($data=="7-3") $birth_name = 'Anatol, Jacek, Korneli, Leon, Mi³os³aw, Otto';
if ($data=="7-4") $birth_name = 'Ageusz, Alfred, Aurelian, El¿bieta, Innocenty, Innocenta, Józef, Julian, Malwina, Malwin, Odo, Teodor, Wielis³aw';
if ($data=="7-5") $birth_name = 'Antoni, Bart³omiej, Filomena, Jakub, Karolina, Micha³, Przybywoj, Szarlota, Wilhelm';
if ($data=="7-6") $birth_name = 'Agrypina, Chociebor, Dominik, Dominika, Goar, Gotard, Lucja, £ucja, Niegos³aw';
if ($data=="7-7") $birth_name = 'Antoni, Benedykt, Cyryl, Estera, Kira, Metody, Piotr, Pompejusz, Sêdzis³awa, Wilibald';
if ($data=="7-8") $birth_name = 'Adrian, Adrianna, Chwalimir, Edgar, El¿bieta, Eugeniusz, Kilian, Prokop, Wirginia';
if ($data=="7-9") $birth_name = 'Anatolia, Hieronim, Lucja, Ludwika, Heloiza, Lukrecja, £ucja, Miko³aj, Patrycjusz, Weronika, Wszeb±d, Zenon, Zenona';
if ($data=="7-10") $birth_name = 'Aleksander, Amelia, Aniela, Filip, January, Radziwoj, Rufina, Samson, Sylwan, Sylwana, Witalis';
if ($data=="7-11") $birth_name = 'Benedykt, Cyprian, Kalina, Kallina, Kir, Olga, Pelagia, Pelagiusz, Pius, Placyd, Sawin, Wyszes³awa';
if ($data=="7-12") $birth_name = 'Andrzej, Euzebiusz, Feliks, Henryk, Jan Gwalbert, Pawe³, Piotr, Tolimir, Weronika';
if ($data=="7-13") $birth_name = 'Ernest, Ernestyn, Eugeniusz, Irwin, Jakub, Justyna, Ma³gorzata, Radomi³a';
if ($data=="7-14") $birth_name = 'Bonawentura, Damian, Dobrogost, Franciszek, Izabela, Kosma, Marceli, Marcelin, Marcelina, Stella, Ulryk, Ulrych, Ulryka';
if ($data=="7-15") $birth_name = 'Daniel, Dawid, Dawida, Egon, Henryk, Ignacy, Iga, Ignacja, ¯egota, Lubomys³, Niecis³aw, W³odzimierz';
if ($data=="7-16") $birth_name = 'Andrzej, Benedykt, Dzier¿ys³aw, Dziers³aw, Eustachy, Eustachiusz, Faust, Maria Magdalena, Marika, Ostap, Ruta, Stefan';
if ($data=="7-17") $birth_name = 'Aleksander, Aleksy, Andrzej, Bogdan, Dzier¿ykraj, Januaria, Julietta, Leon, Marceli, Marcelina, Maria Magdalena';
if ($data=="7-18") $birth_name = 'Arnold, Arnolf, Erwin, Erwina, Kamil, Karolina, Robert, Roberta, Szymon, Unis³aw, Wespazjan';
if ($data=="7-19") $birth_name = 'Alfred, Arseniusz, Lutobor, Rufin, Wincenty, Wodzis³aw';
if ($data=="7-20") $birth_name = 'Czes³aw, Czech, Czechasz, Czechoñ, Eliasz, Heliasz, Hieronim, Leon, Ma³gorzata, Pawe³, Sewera';
if ($data=="7-21") $birth_name = 'Andrzej, Benedykt, Daniel, Paulina, Prakseda, Prokop, Stojs³aw, Wiktor, Wiktoriusz';
if ($data=="7-22") $birth_name = 'Albin, Boles³awa, Bolis³awa, Laurencjusz, Wawrzyniec, Maria Magdalena, Milenia, Pankracy, Wiêcemi³a';
if ($data=="7-23") $birth_name = 'Apolinary, Bogna, ¯elis³aw';
if ($data=="7-24") $birth_name = 'Antoni, Kinga, Krystyna, Kunegunda, Olga, Wojciecha';
if ($data=="7-25") $birth_name = 'Jakub, Krzysztof, Nieznamir, S³awosz, Walentyna';
if ($data=="7-26") $birth_name = 'Anna, Bartolomea, Gra¿yna, Miros³awa';
if ($data=="7-27") $birth_name = 'Alfons, Alfonsyna, Aureli, Julia, Laurenty, Lilla, Marta, Natalia, Natalis, Pantaleon, Rudolf, Rudolfa, Rudolfina, Wszebor';
if ($data=="7-28") $birth_name = 'Innocenty, Innocenta, Marcela, Pantaleon, Samson, ¦wiêtomir, Wiktor, Wiktoriusz';
if ($data=="7-29") $birth_name = 'Beatrycze, Beatrice, Beatryks, Cierpis³aw, Faustyn, Konstantyn, Lucylla, Maria, Marta, Olaf, Serafina, Urban';
if ($data=="7-30") $birth_name = 'Abdon, Julia, Julita, Ludmi³a, Maryna, Ubys³aw';
if ($data=="7-31") $birth_name = 'Beatus, Demokryt, Emilian, Ernesta, Ernestyna, Helena, Ignacy, Iga, Ignacja, ¯egota, Justyn, Ludomir';
if ($data=="8-1") $birth_name = 'Brodzis³aw, Justyn, Konrad, Konrada, Nadia, Piotr';
if ($data=="8-2") $birth_name = 'Alfons, Alfonsyna, Borzys³awa, Gustaw, Ilia, Karina, Maria, Stefan';
if ($data=="8-3") $birth_name = 'August, Augusta, Krzywos±d, Lidia, Nikodem, Symeon, Szczepan';
if ($data=="8-4") $birth_name = 'Alfred, Arystarch, Dominik, Maria, Mironieg, Protazy';
if ($data=="8-5") $birth_name = 'Cyriak, Emil, Karolin, Maria, Nonna, Oswald, Oswalda, Stanis³awa';
if ($data=="8-6") $birth_name = 'Felicysym, Jakub, January, S³awa, Stefan, Sykstus, Wincenty';
if ($data=="8-7") $birth_name = 'Albert, Alberta, Albertyna, Anna, Dobiemir, Donat, Donata, Doris, Dorota, Kajetan';
if ($data=="8-8") $birth_name = 'Cyprian, Cyriak, Cyryl, Emil, Emilian, Emiliusz, Niezamys³, Olech, Sylwiusz';
if ($data=="8-9") $birth_name = 'Jan, Klarysa, Mi³orad, Roland, Roman, Romuald';
if ($data=="8-10") $birth_name = 'Asteria, Bernard, Bogdan, Borys, Filomena, Laurencjusz, Wawrzyniec, Prochor, Wierzchos³aw';
if ($data=="8-11") $birth_name = 'Aleksander, Herman, Ligia, Lukrecja, W³odzimierz, W³odziwoj, Zuzanna, Zula';
if ($data=="8-12") $birth_name = 'B±dzis³aw, Hilaria, Klara, Lech, Leonida, Piotr';
if ($data=="8-13") $birth_name = 'Diana, Dianna, Gertruda, Helena, Hipolit, Hipolita, Jan, Kasjan, Radomi³a, Wojbor';
if ($data=="8-14") $birth_name = 'Alfred, Atanazja, Dobrowój, Euzebiusz, Kalikst, Kaliksta, Machabeusz';
if ($data=="8-15") $birth_name = 'Maria, Napoleon, Stefan, Stella, Trzebimir';
if ($data=="8-16") $birth_name = 'Alfons, Alfonsyna, Ambro¿y, Domarad, Domarat, Joachim, Joachima, Roch';
if ($data=="8-17") $birth_name = 'Anastazja, Angelika, Anita, Bertram, Eliza, Jacek, Jaczewoj, Joanna, Julianna, Liberat, Miron, Zawisza, ¯anna';
if ($data=="8-18") $birth_name = 'Agapit, Bogus³awa, Bronis³aw, Bronisz, Helena, Ilona, Klara, Tworzys³awa';
if ($data=="8-19") $birth_name = 'Boles³aw, Emilia, Jan, Julian, Juliusz, Ludwik, Piotr, Sebald';
if ($data=="8-20") $birth_name = 'Bernard, Jan, Sabin, Samuel, Samuela, Sieciech, Szwieciech, ¦wieciech, Sobies³aw';
if ($data=="8-21") $birth_name = 'Adolf, Adolfa, Adolfina, Alf, Bernard, Emilian, Filipina, Franciszek, Joanna, Kazimiera, Mêcimir';
if ($data=="8-22") $birth_name = 'Cezary, Dalegor, Fabrycjan, Fabrycy, Hipolit, Hipolita, Maria, Namys³aw, Oswald, Oswalda, Tymoteusz, Zygfryd';
if ($data=="8-23") $birth_name = 'Apolinary, Benicjusz, Filip, Laurenty, Sulirad, Walerian, Waleriana, Zacheusz';
if ($data=="8-24") $birth_name = 'Bart³omiej, Cieszymir, Jerzy, Joanna, Malina, Michalina';
if ($data=="8-25") $birth_name = 'Gaudencjusz, Gaudenty, Grzegorz, Ludwik, Luiza, Micha³, Siecies³aw';
if ($data=="8-26") $birth_name = 'Dobroniega, Joanna, Konstanty, Maksym, Maria, Wiktorian, Zefir, Zefiryn, Zefiryna';
if ($data=="8-27") $birth_name = 'Angel, Angelus, Cezary, Gebhard, Józef, Kalasanty, Ma³gorzata, Przybymir, Rufus, Teodor';
if ($data=="8-28") $birth_name = 'Adelina, Aleksander, Aleksy, Augustyn, Patrycja, Sobies³aw, Stronis³aw';
if ($data=="8-29") $birth_name = 'Flora, Jan, Racibor, Sabina';
if ($data=="8-30") $birth_name = 'Adaukt, Czêstowoj, Gaudencja, Miron, Rebeka, Ró¿a, Szczêsny, Szczêsna, Tekla';
if ($data=="8-31") $birth_name = 'Bohdan, Paulina, Rajmund, Rajmunda, ¦wiêtos³aw';
if ($data=="9-1") $birth_name = 'Bronis³aw, Bronisz, Bronis³awa, Idzi';
if ($data=="9-2") $birth_name = 'Absalon, Bohdan, Czes³aw, Czech, Czechasz, Czechoñ, Ders³aw, Dionizy, Eliza, Henryk, Julian, Stefan, Tobiasz, Wilhelm, Witomys³';
if ($data=="9-3") $birth_name = 'Antoni, Bart³omiej, Bazylissa, Bronis³aw, Bronisz, Erazma, Eufemia, Eufrozyna, Izabela, Jan, Joachim, Joachima, Manswet, Mojmir, Szymon, Wincenty, Zenon, Zenona';
if ($data=="9-4") $birth_name = 'Agatonik, Ida, Lilianna, Ro¶cigniew, Rozalia, Ró¿a';
if ($data=="9-5") $birth_name = 'Dorota, Herakles, Herkules, Herkulan, Justyna, Laurencjusz, Wawrzyniec, Stronis³awa';
if ($data=="9-6") $birth_name = 'Albin, Beata, Eugenia, Eugeniusz, Magnus, Micha³, Uniewit, Zachariasz';
if ($data=="9-7") $birth_name = 'Domas³awa, Domis³awa, Marek, Melchior, Regina, Rena, Ryszard';
if ($data=="9-8") $birth_name = 'Adrian, Adrianna, Klementyna, Maria, Nestor, Rados³aw, Rados³awa';
if ($data=="9-9") $birth_name = 'Augustyna, Aureliusz, Dionizy, Gorgoncjusz, Pimen, Piotr, Sergiusz, Sobies±d, ¦cibor, ¦cibora';
if ($data=="9-10") $birth_name = 'Aldona, £ukasz, Miko³aj, M¶cibor, Pulcheria';
if ($data=="9-11") $birth_name = 'Feliks, Jacek, Jan, Naczes³aw, Prot';
if ($data=="9-12") $birth_name = 'Amadeusz, Amedeusz, Cyrus, Gwidon, Maria, Piotr, Radzimir, Sylwin';
if ($data=="9-13") $birth_name = 'Aleksander, Aureliusz, Eugenia, Filip, Lubor, Materna, Morzys³aw, Szeliga';
if ($data=="9-14") $birth_name = 'Bernard, Cyprian, Roksana, Siemomys³, Szymon';
if ($data=="9-15") $birth_name = 'Albin, Budzigniew, Maria, Nikodem';
if ($data=="9-16") $birth_name = 'Antym, Cyprian, Edyta, Edda, Eufemia, Eugenia, Franciszek, Jakobina, Kamila, Kornel, Lucja, £ucja, Sebastiana, Sêdzis³aw, Wiktor, Wiktoriusz';
if ($data=="9-17") $birth_name = 'Ariadna, Dezyderiusz, Drogos³aw, Franciszek, Hildegarda, Justyn, Justyna, Lambert, Lamberta, Narcyz, Teodora';
if ($data=="9-18") $birth_name = 'Dobrowit, Irena, Irma, Józef, Ryszarda, Stefania, Tytus, Zachariasz';
if ($data=="9-19") $birth_name = 'Alfons, Alfonsyna, January, Konstancja, Sydonia, Teodor, Wiêcemir';
if ($data=="9-20") $birth_name = 'Dionizy, Eustachy, Eustachiusz, Fausta, Faustyna, Filipina, Irena, Oleg, Ostap, Sozant';
if ($data=="9-21") $birth_name = 'Bo¿eciech, Bo¿ydar, Hipolit, Hipolita, Ifigenia, Jonasz, Laurenty, Mateusz, Mira';
if ($data=="9-22") $birth_name = 'Joachim, Joachima, Maurycy, Prosimir, Tomasz';
if ($data=="9-23") $birth_name = 'Boguchwa³a, Bogus³aw, Libert, Minodora, Tekla';
if ($data=="9-24") $birth_name = 'Gerard, Gerarda, Gerhard, Maria, Teodor, Tomir, Uniegost';
if ($data=="9-25") $birth_name = 'Aureli, Aurelia, Aurelian, Franciszek, Gaspar, Herkulan, Kamil, Kleofas, Kleopatra, £adys³aw, Piotr, Rufus, ¦wiêtope³k, Wincenty, W³adys³aw, W³adys³awa, W³odzis³aw';
if ($data=="9-26") $birth_name = 'Cyprian, Euzebiusz, Justyna, £êkomir';
if ($data=="9-27") $birth_name = 'Amadeusz, Amedeusz, Damian, Kosma, Przedbor, Urban';
if ($data=="9-28") $birth_name = 'Jan, Laurencjusz, Wawrzyniec, Luba, Lubosza, Marek, Nikita, Salomon, Sylwin, Wac³aw, Wac³awa, Wiêces³aw';
if ($data=="9-29") $birth_name = 'Dad¼bog, Franciszek, Michalina';
if ($data=="9-30") $birth_name = 'Grzegorz, Hieronim, Honoriusz, Imis³aw, Leopard, Sofia, Wera, Wiera, Wiktor, Wiktoriusz, Zofia';
if ($data=="10-1") $birth_name = 'Benigna, Cieszys³aw, Danuta, Dan, Danisz, Igor, Jan, Remigiusz';
if ($data=="10-2") $birth_name = 'Dionizy, Leodegar, Stanimir, Teofil, Trofim';
if ($data=="10-3") $birth_name = 'Eustachy, Eustachiusz, Ewald, Gerard, Gerarda, Gerhard, Heliodor, Józefa, Kandyd, Sieros³aw, Teresa';
if ($data=="10-4") $birth_name = 'Edwin, Franciszek, Konrad, Konrada, Manfred, Manfreda, Rozalia';
if ($data=="10-5") $birth_name = 'Apolinary, Czêstogniew, Donat, Donata, Faust, Fides, Flawia, Igor, Justyn, Konstancjusz, Konstans, Placyd';
if ($data=="10-6") $birth_name = 'Artur, Artus, Bronis³aw, Bronisz, Brunon, Emil, Fryderyka, Roman';
if ($data=="10-7") $birth_name = 'Amalia, Justyna, Maria, Marek, Ro¶cis³awa, Stefan, Tekla';
if ($data=="10-8") $birth_name = 'Artemon, Brygida, Bryda, Demetriusz, Laurencja, Marcin, Pelagia, Pelagiusz, Symeon, Wojs³awa';
if ($data=="10-9") $birth_name = 'Arnold, Arnolf, Atanazja, Bogdan, Dionizjusz, Dionizy, Jan, Ludwik, Przedpe³k';
if ($data=="10-10") $birth_name = 'Franciszek, German, Kalistrat, Lutomir, Paulin, Tomi³';
if ($data=="10-11") $birth_name = 'Aldona, Brunon, Burchard, Dobromi³a, Emil, Emilian, Emiliusz, Germanik, Maria, Marian, Placydia';
if ($data=="10-12") $birth_name = 'Cyriak, Eustachy, Eustachiusz, Grzymis³aw, Maksymilian, Ostap, Salwin, Serafin, Witold, Witolda, Wito³d';
if ($data=="10-13") $birth_name = 'Daniel, Edward, Gerald, Geraldyna, Maurycy, Miko³aj, Siemis³aw, Teofil';
if ($data=="10-14") $birth_name = 'Alan, Bernard, Dominik, Dzier¿ymir, Fortunata, Kalikst, Kaliksta';
if ($data=="10-15") $birth_name = 'Brunon, Go¶cis³awa, Jadwiga, Sewer, Tekla, Teresa';
if ($data=="10-16") $birth_name = 'Ambro¿y, Aurelia, Dionizy, Florentyna, Galla, Gallina, Gawe³, Gerard, Gerarda, Gerhard, Grzegorz, Radzis³aw';
if ($data=="10-17") $birth_name = 'Lucyna, Ma³gorzata, Marian, Sulis³awa, Wiktor, Wiktoriusz';
if ($data=="10-18") $birth_name = 'Julian, £ukasz, René';
if ($data=="10-19") $birth_name = 'Ferdynand, Fryda, Pelagia, Pelagiusz, Piotr, Siemowit, Skarbimir, Toma, Ziemowit';
if ($data=="10-20") $birth_name = 'Budzis³awa, Irena, Jan Kanty, Kleopatra, Wendelin, Witalis';
if ($data=="10-21") $birth_name = 'Bernard, Celina, Dobromi³, El¿bieta, Hilary, Klemencja, Pelagia, Pelagiusz, Urszula, Wszebora';
if ($data=="10-22") $birth_name = 'Abercjusz, Filip, Halka, Kordula, Kordelia, Przybys³awa, Sewer';
if ($data=="10-23") $birth_name = 'Ignacy, Iga, Ignacja, ¯egota, Jan, Marlena, Odilla, Roman, Seweryn, Teodor, W³o¶cis³aw';
if ($data=="10-24") $birth_name = 'Antoni, Boleczest, Filip, Hortensja, Marcin, Rafa³, Rafaela, Salomon';
if ($data=="10-25") $birth_name = 'Bonifacy, Boñcza, Chryzant, Daria, Inga, Kryspin, Maur, Sambor, Taras, Teodozjusz, Wilhelmina';
if ($data=="10-26") $birth_name = 'Dymitriusz, Ewaryst, Eweryst, Lucyna, Ludmi³a, Lutos³aw, £ucjan';
if ($data=="10-27") $birth_name = 'Frumencjusz, Iwona, Sabina, Siestrzemi³, Wincenty';
if ($data=="10-28") $birth_name = 'Juda, Szymon, Tadeusz, Wszeciech';
if ($data=="10-29") $birth_name = 'Euzebia, Franciszek, Longin, Longina, Lubogost, Narcyz, Teodor, Wioletta';
if ($data=="10-30") $birth_name = 'Alfons, Alfonsyna, Angel, Angelus, Edmund, Klaudiusz, Przemys³aw, S±dos³aw, Zenobia';
if ($data=="10-31") $birth_name = 'Alfons, Alfonsyna, Antoni, Antonina, August, Augusta, Godzimir, Godzisz, Lucylla, £ukasz, Saturnin, Saturnina, Urban, Wolfgang';
if ($data=="11-1") $birth_name = 'Andrzej, Konradyn, Konradyna, Seweryn, Warcis³aw, Wiktoryna';
if ($data=="11-2") $birth_name = 'Ambro¿y, Bohdana, Bo¿ydar, Eudoksjusz, Ma³gorzata, Stojmir, Tobiasz, Wiktoryn';
if ($data=="11-3") $birth_name = 'Bogumi³, Cezary, Chwalis³aw, Hubert, Huberta, Sylwia';
if ($data=="11-4") $birth_name = 'Emeryk, Karol Boromeusz, M¶ciwój, Olgierd, Witalis';
if ($data=="11-5") $birth_name = 'Blandyn, Blandyna, Dalemir, El¿bieta, Florian, Modesta, S³awomir, Zachariasz';
if ($data=="11-6") $birth_name = 'Feliks, Leonard, Trzebowit, Ziemowit';
if ($data=="11-7") $birth_name = 'Achilles, Antoni, Engelbert, Florentyn, Melchior, Przemi³';
if ($data=="11-8") $birth_name = 'Dymitr, Gotfryd, Godfryd, Hadrian, Klaudiusz, Sewer, Sewerian, Seweryn, Sêdziwoj, Wiktor, Wiktoriusz, Wiktoryn';
if ($data=="11-9") $birth_name = 'Bogudar, Genowefa, Nestor, Teodor, Ursyn';
if ($data=="11-10") $birth_name = 'Andrzej, Lena, Leon, Ludomir, Nelly, Nimfa, Probus, Stefan';
if ($data=="11-11") $birth_name = 'Anastazja, Bart³omiej, Maciej, Marcin, Prot, Spycis³aw, Teodor';
if ($data=="11-12") $birth_name = 'Czcibor, Cibor, Izaak, Jonasz, Jozafat, Konradyn, Konradyna, Krystyn, Marcin, Renata, Renat, Witold, Witolda, Wito³d';
if ($data=="11-13") $birth_name = 'Arkadiusz, Arkady, Brykcjusz, Eugeniusz, Jan, Miko³aj, Stanis³aw, Walentyn';
if ($data=="11-14") $birth_name = 'Agata, Aga, Damian, El¿bieta, Emil, Emiliusz, Jozafat, Józef, Judyta, Kosma, Laurenty, Lewin, Serafin, ¦cibor, ¦cibora, Wszerad';
if ($data=="11-15") $birth_name = 'Albert, Alberta, Albertyna, Artur, Artus, Idalia, Leopold, Leopoldyna, Przybygniew, Roger';
if ($data=="11-16") $birth_name = 'Aureliusz, Dionizy, Edmund, Gertruda, Leon, Maria, Marek, Niedamir, Otomar, Pawe³, Piotr';
if ($data=="11-17") $birth_name = 'Dionizy, Floryn, Grzegorz, Hugo, Hugon, Salomea, Salome, Sulibor, Zbys³aw';
if ($data=="11-18") $birth_name = 'Aniela, Cieszymys³, Filipina, Galezy, Klaudyna, Odo, Otto, Roman, Tomasz';
if ($data=="11-19") $birth_name = 'El¿bieta, Mironiega, Pawe³, Seweryn, Seweryna';
if ($data=="11-20") $birth_name = 'Anatol, Edmund, Feliks, Jeron, Oktawiusz, Sêdzimir';
if ($data=="11-21") $birth_name = 'Albert, Alberta, Albertyna, Janusz, Konrad, Konrada, Maria, Piotr, Regina, Rena, Rufus, Twardos³aw, Wies³aw';
if ($data=="11-22") $birth_name = 'Cecylia, Marek, Maur, Wszemi³a';
if ($data=="11-23") $birth_name = 'Adela, Erast, Felicyta, Klemens, Klementyn, Orestes, Przedwoj';
if ($data=="11-24") $birth_name = 'Dobros³aw, Emilia, Emma, Flora, Franciszek, Gerard, Gerarda, Gerhard, Jan, Mina, Pêcis³aw, Protazy';
if ($data=="11-25") $birth_name = 'Erazm, Jozafat, Katarzyna, Têgomir';
if ($data=="11-26") $birth_name = 'Delfin, Dobiemiest, Jan, Konrad, Konrada, Lechos³aw, Lechos³awa, Leonard, Sylwester';
if ($data=="11-27") $birth_name = 'Damazy, Dominik, Leonard, Maksymilian, Oda, Stojgniew, Walery, Wirgiliusz';
if ($data=="11-28") $birth_name = 'Go¶cirad, Grzegorz, Jakub, Les³aw, Les³awa, Rufin, Zdzis³aw';
if ($data=="11-29") $birth_name = 'B³a¿ej, Bolemys³, Fryderyk, Przemys³, Saturnin, Saturnina, Walter';
if ($data=="11-30") $birth_name = 'Andrzej, Justyna, Konstanty, Maura, Zbys³awa';
if ($data=="12-1") $birth_name = 'D³ugosz, Edmund, Eligiusz, Eliga, Iwa, Natalia, Natalis, Platon, Sobies³awa';
if ($data=="12-2") $birth_name = 'Adria, Aurelia, Balbina, Bibianna, Paulina, Sulis³aw, Wiktoryn, Zbylut';
if ($data=="12-3") $birth_name = 'Franciszek, Kasjan, Ksawery, Lucjusz, Unimir';
if ($data=="12-4") $birth_name = 'Barbara, Berno, Biernat, Chrystian, Hieronim, Krystian, Piotr';
if ($data=="12-5") $birth_name = 'Anastazy, Gerald, Geraldyna, Kryspina, Krystyna, Pêcis³awa, Saba';
if ($data=="12-6") $birth_name = 'Dionizja, Emilian, Jarema, Jarogniew, Miko³aj';
if ($data=="12-7") $birth_name = 'Agaton, Ambro¿y, Marcin, Ninomys³';
if ($data=="12-8") $birth_name = 'Boguwola, Klement, Maria, ¦wiatozar, Wirginiusz';
if ($data=="12-9") $birth_name = 'Delfina, Joachim, Joachima, Leokadia, Loda, Waleria, Wielis³awa, Wies³aw';
if ($data=="12-10") $birth_name = 'Andrzej, Daniel, Judyta, Julia, Maria, Radzis³awa';
if ($data=="12-11") $birth_name = 'Damazy, Daniela, Julia, Stefan, Waldemar, Wojmir';
if ($data=="12-12") $birth_name = 'Adelajda, Aleksander, Dagmara, Paramon, Suliwoj';
if ($data=="12-13") $birth_name = 'Lucja, £ucja, Otylia, W³odzis³awa';
if ($data=="12-14") $birth_name = 'Alfred, Arseniusz, Izydor, Naum, Pompejusz, S³awobor, Spirydion';
if ($data=="12-15") $birth_name = 'Celina, Fortunata, Ignacy, Iga, Ignacja, ¯egota, Krystiana, Nina, Walerian, Waleriana, Wolimir';
if ($data=="12-16") $birth_name = 'Adelajda, Ado, Albina, Alina, Ananiasz, Bean, Zdzis³awa';
if ($data=="12-17") $birth_name = 'Florian, Jolanta, £azarz, Olimpia, Warwara, ¯yros³aw';
if ($data=="12-18") $birth_name = 'Bogus³aw, Gracjan, Gracjana, Laurencja, Wilibald, Wszemir';
if ($data=="12-19") $birth_name = 'Abraham, Beniamin, Dariusz, Gabriela, M¶cigniew, Nemezjusz, Tymoteusz, Urban';
if ($data=="12-20") $birth_name = 'Amon, Bogumi³a, Dominik, Liberat, Teofil';
if ($data=="12-21") $birth_name = 'Balbin, Festus, Honorat, Tomasz, Tomis³aw';
if ($data=="12-22") $birth_name = 'Beata, Drogomir, Flawian, Franciszka, Gryzelda, Honorata, Ksawera, Ksaweryna, Zenon, Zenona';
if ($data=="12-23") $birth_name = 'Dagobert, Mina, S³awomir, S³awomira, Wiktoria';
if ($data=="12-24") $birth_name = 'Adam, Ada, Adamina, Adela, Ewa, Ewelina, Ewelin, Godzis³awa, Grzegorz, Grzymis³awa, Hermina, Herminia, Irma, Irmina, Zenobiusz';
if ($data=="12-25") $birth_name = 'Anastazja, Eugenia, Piotr, Spirydion';
if ($data=="12-26") $birth_name = 'Dionizy, Szczepan, Wróciwoj';
if ($data=="12-27") $birth_name = 'Cezary, Fabiola, Fabia, Jan, Radomys³';
if ($data=="12-28") $birth_name = 'Antoni, Dobrowiest, Emma, Godzis³aw, Teofila';
if ($data=="12-29") $birth_name = 'Domawit, Dominik, Gos³aw, Jonatan, Marcin, Tomasz, Trofim';
if ($data=="12-30") $birth_name = 'Dawid, Dawida, Dionizy, Eugeniusz, Irmina, Katarzyna, £azarz, Rainer, Sabin, Sewer, Uniedrog';
if ($data=="12-31") $birth_name = 'Korneliusz, Mariusz, Melania, Sebastian, Sylwester, Tworzys³aw';

?>